name: 'Python env setup'
description: 'Standard setup for Python environment'
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Install Python
      shell: bash
      run: uv python install 3.13
    - name: Install dependencies
      shell: bash
      run: uv sync --all-extras --dev
